/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.City;
import model.Community;
import model.Encounter;
import model.EncounterHistory;
import model.House;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Patient;
import model.PatientDirectory;
import model.Person;
import model.PersonDirectory;
import model.VitalSigns;
import java.util.regex.*;
import javax.naming.InvalidNameException;

/**
 *
 * @author sindhusrinivas
 */
public class PersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    private PersonDirectory personDirectory;
    Person person;
    House house;
    PatientDirectory pd;
    HashMap<String, Patient> map = pd.map;

    public PersonJPanel(PersonDirectory personDirectory) {
        initComponents();
        this.personDirectory = personDirectory;
//        this.house = house;

        setDefaultOptions();
        populateTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPerson = new javax.swing.JTable();
        CreatePanel = new javax.swing.JPanel();
        lblCreate = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblCommunity = new javax.swing.JLabel();
        lblHouse = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtCommunity = new javax.swing.JTextField();
        txtHouse = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        lblnamevali = new javax.swing.JLabel();
        lblagevali = new javax.swing.JLabel();
        lblcityvali = new javax.swing.JLabel();
        ViewPanel = new javax.swing.JPanel();
        lbView = new javax.swing.JLabel();
        lblName1 = new javax.swing.JLabel();
        lblAge1 = new javax.swing.JLabel();
        lblCity1 = new javax.swing.JLabel();
        lblCommunity1 = new javax.swing.JLabel();
        lblHouse1 = new javax.swing.JLabel();
        txtName1 = new javax.swing.JTextField();
        txtAge1 = new javax.swing.JTextField();
        txtCity1 = new javax.swing.JTextField();
        txtCommunity1 = new javax.swing.JTextField();
        txtHouse1 = new javax.swing.JTextField();
        UpdatePanel = new javax.swing.JPanel();
        lblUpdate = new javax.swing.JLabel();
        lblName6 = new javax.swing.JLabel();
        lblAge6 = new javax.swing.JLabel();
        lblCity6 = new javax.swing.JLabel();
        lblCommunity6 = new javax.swing.JLabel();
        lblHouse6 = new javax.swing.JLabel();
        txtName6 = new javax.swing.JTextField();
        txtAge6 = new javax.swing.JTextField();
        txtCity6 = new javax.swing.JTextField();
        txtCommunity6 = new javax.swing.JTextField();
        txtHouse6 = new javax.swing.JTextField();
        btnUpdate1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(213, 77, 77));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MANAGE PERSON");

        btnCreate.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnCreate.setText("CREATE ");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnView.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnView.setText("VIEW");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        tblPerson.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NAME", "AGE", "CITY", "COMMUNITY", "HOUSE NO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPerson);

        CreatePanel.setBackground(new java.awt.Color(255, 255, 255));

        lblCreate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblCreate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreate.setText("Create Person Details:");
        lblCreate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblName.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblName.setText("Name:");

        lblAge.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblAge.setText("Age:");

        lblCity.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblCity.setText("City:");

        lblCommunity.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblCommunity.setText("Community:");

        lblHouse.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblHouse.setText("House No:");

        txtName.setBackground(new java.awt.Color(204, 204, 204));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
        });

        txtAge.setBackground(new java.awt.Color(204, 204, 204));
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAgeKeyPressed(evt);
            }
        });

        txtCity.setBackground(new java.awt.Color(204, 204, 204));
        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });
        txtCity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCityKeyPressed(evt);
            }
        });

        txtCommunity.setBackground(new java.awt.Color(204, 204, 204));

        txtHouse.setBackground(new java.awt.Color(204, 204, 204));
        txtHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHouseActionPerformed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CreatePanelLayout = new javax.swing.GroupLayout(CreatePanel);
        CreatePanel.setLayout(CreatePanelLayout);
        CreatePanelLayout.setHorizontalGroup(
            CreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreatePanelLayout.createSequentialGroup()
                        .addComponent(lblHouse)
                        .addGap(18, 18, 18)
                        .addComponent(txtHouse, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CreatePanelLayout.createSequentialGroup()
                        .addGroup(CreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAge)
                            .addComponent(lblCity)
                            .addComponent(lblCommunity))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(CreatePanelLayout.createSequentialGroup()
                                .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblcityvali))
                            .addGroup(CreatePanelLayout.createSequentialGroup()
                                .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblagevali))
                            .addGroup(CreatePanelLayout.createSequentialGroup()
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblnamevali)))))
                .addContainerGap(66, Short.MAX_VALUE))
            .addComponent(lblCreate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreatePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addGap(94, 94, 94))
        );
        CreatePanelLayout.setVerticalGroup(
            CreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreatePanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(CreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnamevali))
                .addGap(15, 15, 15)
                .addGroup(CreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblagevali))
                .addGap(15, 15, 15)
                .addGroup(CreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcityvali))
                .addGap(15, 15, 15)
                .addGroup(CreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCommunity)
                    .addComponent(txtCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(CreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHouse)
                    .addComponent(txtHouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ViewPanel.setBackground(new java.awt.Color(255, 255, 255));
        ViewPanel.setPreferredSize(new java.awt.Dimension(315, 319));

        lbView.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbView.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbView.setText("View Person Details:");
        lbView.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblName1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblName1.setText("Name:");

        lblAge1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblAge1.setText("Age:");

        lblCity1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblCity1.setText("City:");

        lblCommunity1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblCommunity1.setText("Community:");

        lblHouse1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblHouse1.setText("House No:");

        txtName1.setBackground(new java.awt.Color(204, 204, 204));
        txtName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtName1ActionPerformed(evt);
            }
        });

        txtAge1.setBackground(new java.awt.Color(204, 204, 204));
        txtAge1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAge1ActionPerformed(evt);
            }
        });

        txtCity1.setBackground(new java.awt.Color(204, 204, 204));
        txtCity1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCity1ActionPerformed(evt);
            }
        });

        txtCommunity1.setBackground(new java.awt.Color(204, 204, 204));

        txtHouse1.setBackground(new java.awt.Color(204, 204, 204));
        txtHouse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHouse1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ViewPanelLayout = new javax.swing.GroupLayout(ViewPanel);
        ViewPanel.setLayout(ViewPanelLayout);
        ViewPanelLayout.setHorizontalGroup(
            ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewPanelLayout.createSequentialGroup()
                .addComponent(lbView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(ViewPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCommunity1)
                    .addComponent(lblHouse1)
                    .addComponent(lblCity1)
                    .addComponent(lblAge1)
                    .addComponent(lblName1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAge1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCity1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCommunity1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHouse1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        ViewPanelLayout.setVerticalGroup(
            ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbView, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge1)
                    .addComponent(txtAge1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity1)
                    .addComponent(txtCity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCommunity1)
                    .addComponent(txtCommunity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHouse1)
                    .addComponent(txtHouse1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        UpdatePanel.setBackground(new java.awt.Color(255, 255, 255));

        lblUpdate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblUpdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUpdate.setText("Update Person Details:");
        lblUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblName6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblName6.setText("Name:");

        lblAge6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblAge6.setText("Age:");

        lblCity6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblCity6.setText("City:");

        lblCommunity6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblCommunity6.setText("Community:");

        lblHouse6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblHouse6.setText("House No:");

        txtName6.setBackground(new java.awt.Color(204, 204, 204));
        txtName6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtName6ActionPerformed(evt);
            }
        });

        txtAge6.setBackground(new java.awt.Color(204, 204, 204));
        txtAge6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAge6ActionPerformed(evt);
            }
        });

        txtCity6.setBackground(new java.awt.Color(204, 204, 204));
        txtCity6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCity6ActionPerformed(evt);
            }
        });

        txtCommunity6.setBackground(new java.awt.Color(204, 204, 204));

        txtHouse6.setBackground(new java.awt.Color(204, 204, 204));
        txtHouse6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHouse6ActionPerformed(evt);
            }
        });

        btnUpdate1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        btnUpdate1.setText("Update");
        btnUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UpdatePanelLayout = new javax.swing.GroupLayout(UpdatePanel);
        UpdatePanel.setLayout(UpdatePanelLayout);
        UpdatePanelLayout.setHorizontalGroup(
            UpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdatePanelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(UpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAge6)
                    .addComponent(lblCity6)
                    .addComponent(lblCommunity6)
                    .addComponent(lblHouse6))
                .addGap(35, 35, 35)
                .addGroup(UpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtName6)
                    .addComponent(txtAge6)
                    .addComponent(txtCity6)
                    .addComponent(txtCommunity6)
                    .addComponent(txtHouse6, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lblUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdatePanelLayout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(btnUpdate1)
                .addGap(113, 113, 113))
        );
        UpdatePanelLayout.setVerticalGroup(
            UpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdatePanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(UpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(UpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge6)
                    .addComponent(txtAge6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(UpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity6)
                    .addComponent(txtCity6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(UpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCommunity6)
                    .addComponent(txtCommunity6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(UpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHouse6)
                    .addComponent(txtHouse6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdate1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(UpdatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ViewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CreatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 156, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCreate)
                        .addGap(86, 86, 86)
                        .addComponent(btnView)
                        .addGap(107, 107, 107)
                        .addComponent(btnUpdate)
                        .addGap(77, 77, 77)
                        .addComponent(btnDelete))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCreate, btnDelete, btnUpdate, btnView});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate)
                    .addComponent(btnView)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CreatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ViewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(UpdatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCreate, btnDelete, btnUpdate, btnView});

    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        setDefaultOptions();
        CreatePanel.setVisible(true);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:

        int selectedRowIndex = tblPerson.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to Update.");
            return;
        }

        setDefaultOptions();
        UpdatePanel.setVisible(true);

        DefaultTableModel model = (DefaultTableModel) tblPerson.getModel();
        Person person = (Person) tblPerson.getValueAt(selectedRowIndex, 0);
        House house = person.getHouse();
//        House house = ( House) tblPerson.getValueAt(selectedRowIndex, 0);
        txtName6.setText(person.toString());
        txtAge6.setText(person.getAge());
        txtCity6.setText(house.getCityName());
        txtCommunity6.setText(house.getCommunityName());
        txtHouse6.setText(String.valueOf(house.getHouseNo()));
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void txtHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHouseActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_txtHouseActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
//        Person person1 = personDirectory.addNewPerson();

        String serialregex = "^[A-Za-z]$";
        String intregex = "[0-9]+";
        String regex = "^[0-9]{1,2} " + " [A-Z a-z]{1,20}$";
        if ((txtName.getText().isEmpty() || txtCommunity.getText().isEmpty() || txtCity.getText().isEmpty() || txtAge.getText().isEmpty() || txtHouse.getText().isEmpty())) {
            JOptionPane.showMessageDialog(this, "Enter All Details");
        } else {
            int houseNo;
            String Nameregex = "^[A-Za-z]\\w{1,29}$";
            String houseRegex = "[0-9]+";
            String personName = (txtName.getText());
            String age = (txtAge.getText());
            String community = (txtCommunity.getText());
            String city = (txtCity.getText());
            if (!personName.matches(Nameregex) || (personName.isEmpty())) {
                JOptionPane.showMessageDialog(this, "Enter Proper Name");
                return;
            }
            if (!community.matches(Nameregex) || (community.isEmpty())) {
                JOptionPane.showMessageDialog(this, "Enter Proper community Name");
                return;
            }
            if (!city.matches(Nameregex) || (city.isEmpty())) {
                JOptionPane.showMessageDialog(this, "Enter Proper city Name");
                return;
            }
//            boolean ageValid = true;
//            String s[] = age.split(" ");
////            List range = new ArrayList<>();
////            range.add("days");
////            range.add("months");
////            range.add("years");
//            if (s.length > 1 && s.length < 3) {
//                if (Integer.parseInt(s[0]) < 0) {
//                    JOptionPane.showMessageDialog(this, "Enter Proper Age");
//                    return;
//                }
//
////                if (!range.contains(s[1])) {
////                    JOptionPane.showMessageDialog(this, "Enter Proper Age");
////                    return;
////                }
//            } 
//            
//            else {
//                JOptionPane.showMessageDialog(this, "Enter Proper Age");
//                return;
//            }

            try {
                Integer.parseInt(txtHouse.getText());
                //System.out.println(txtHouse.getText() + " is a valid integer");
            } catch (NumberFormatException e) {
                //System.out.println(txtHouse.getText() + " is not a valid integer");
                JOptionPane.showMessageDialog(this, "Enter Proper House No");
                return;
            }
            houseNo = Integer.parseInt(txtHouse.getText());
            Patient patient = new Patient();
            Encounter encounter = new Encounter();
            EncounterHistory encounterHistory = new EncounterHistory();
            VitalSigns vitalSigns = new VitalSigns();
            Person person = personDirectory.addNewPerson();
            String ag = patient.ageCalculate(age);
            person.setAgeGroup(ag);
            person.setPersonName(personName);
            person.setAge(age);
            House house = new House();
            house.setCityName(city);
            house.setCommunityName(community);
            house.setHouseNo(houseNo);
            house.setSetPerson(person);
            house.setCommunityList(house);
            house.setHouseList(house);
            person.setHouse(house);

            JOptionPane.showMessageDialog(this, "New Person Details added!");

            txtName.setText("");
            txtAge.setText("");
            txtCity.setText("");
            txtCommunity.setText("");
            txtHouse.setText("");
            populateTable();
            revalidate();
            repaint();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    public void ageValidation(String age) throws InvalidNameException {
        try {

        } catch (ArrayIndexOutOfBoundsException e) {
            throw new InvalidNameException("Missing space in age");
//                JOptionPane.showMessageDialog(this, "Missing space in Age");
        }
    }
    private void txtName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName1ActionPerformed

    private void txtAge1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAge1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAge1ActionPerformed

    private void txtCity1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCity1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCity1ActionPerformed

    private void txtHouse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHouse1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHouse1ActionPerformed

    private void txtName6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtName6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName6ActionPerformed

    private void txtAge6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAge6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAge6ActionPerformed

    private void txtCity6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCity6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCity6ActionPerformed

    private void txtHouse6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHouse6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHouse6ActionPerformed

    private void btnUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate1ActionPerformed
        // TODO add your handling code here:

        int selectedRowIndex = tblPerson.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tblPerson.getModel();
        Person person = (Person) model.getValueAt(selectedRowIndex, 0);

        String serialregex = "^[A-Za-z]$";
        String intregex = "[0-9]+";
        String regex = "^[0-9]{1,2} " + " [A-Z a-z]{1,20}$";
        if ((txtName6.getText().isEmpty() || txtCommunity6.getText().isEmpty() || txtCity6.getText().isEmpty() || txtAge6.getText().isEmpty() || txtHouse6.getText().isEmpty())) {
            JOptionPane.showMessageDialog(this, "Enter All Details");
        } else {
            int houseNo;
            String Nameregex = "^[A-Za-z]\\w{1,29}$";
            String personName = (txtName6.getText());
            String age = (txtAge6.getText());
            String community = (txtCommunity6.getText());
            String city = (txtCity6.getText());
            if (!personName.matches(Nameregex) || (personName.isEmpty())) {
                JOptionPane.showMessageDialog(this, "Enter Proper Name");
                return;
            }

            String s[] = age.split(" ");
            List range = new ArrayList<>();
            range.add("days");
            range.add("months");
            range.add("years");
//            if (s.length > 1 && s.length < 3) {
//                if (Integer.parseInt(s[0]) < 0) {
//                    JOptionPane.showMessageDialog(this, "Enter Proper Age");
//                    return;
//                }
//                if (!range.contains(s[1])) {
//                    JOptionPane.showMessageDialog(this, "Enter Proper Age");
//                    return;
//                }
//            } else {
//                JOptionPane.showMessageDialog(this, "Enter Proper Age");
//                return;
//            }
            if (!city.matches(Nameregex) || (city.isEmpty())) {
                JOptionPane.showMessageDialog(this, "Enter Proper city Name");
                return;
            }
            if (!community.matches(Nameregex) || (community.isEmpty())) {
                JOptionPane.showMessageDialog(this, "Enter Proper community Name");
                return;
            }
            try {
                Integer.parseInt(txtHouse6.getText());
//                System.out.println(txtHouse.getText() + " is a valid integer");
            } catch (NumberFormatException e) {
//                System.out.println(txtHouse.getText() + " is not a valid integer");
                JOptionPane.showMessageDialog(this, "Enter Proper House No");
                return;
            }
            Update(person);

            populateTable();

            revalidate();
            repaint();
        }

    }//GEN-LAST:event_btnUpdate1ActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:

        int selectedRowIndex = tblPerson.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to View.");
            return;
        }

        setDefaultOptions();
        ViewPanel.setVisible(true);

        DefaultTableModel model = (DefaultTableModel) tblPerson.getModel();
        Person p = (Person) tblPerson.getValueAt(selectedRowIndex, 0);
        House house = p.getHouse();
//        House house = ( House) tblPerson.getValueAt(selectedRowIndex, 0);
        txtName1.setText(p.toString());
        txtAge1.setText(p.getAge());
        txtCity1.setText(house.getCityName());
        txtCommunity1.setText(house.getCommunityName());
        txtHouse1.setText(String.valueOf(house.getHouseNo()));

        revalidate();
        repaint();

    }//GEN-LAST:event_btnViewActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblPerson.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblPerson.getModel();
        Person person = (Person) model.getValueAt(selectedRowIndex, 0);

        personDirectory.deletePerson(person);

        JOptionPane.showMessageDialog(this, "Person Details Deleted.");

        populateTable();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed

        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            txtName.setEditable(false);
            lblnamevali.setText("Enter names only!");
        } else {
            txtName.setEditable(true);
            lblnamevali.setText("");
        }
    }//GEN-LAST:event_txtNameKeyPressed

    private void txtAgeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyPressed
        // TODO add your handling code here:
          char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            txtAge.setEditable(false);
            lblagevali.setText("Enter valid age!");
        } else {
            txtAge.setEditable(true);
            lblagevali.setText("");
        }
    }//GEN-LAST:event_txtAgeKeyPressed

    private void txtCityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCityKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            txtCity.setEditable(false);
            lblcityvali.setText("Enter valid city names only!");
        } else {
            txtCity.setEditable(true);
            lblcityvali.setText("");
        }
    }//GEN-LAST:event_txtCityKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CreatePanel;
    private javax.swing.JPanel UpdatePanel;
    private javax.swing.JPanel ViewPanel;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbView;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblAge1;
    private javax.swing.JLabel lblAge6;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCity1;
    private javax.swing.JLabel lblCity6;
    private javax.swing.JLabel lblCommunity;
    private javax.swing.JLabel lblCommunity1;
    private javax.swing.JLabel lblCommunity6;
    private javax.swing.JLabel lblCreate;
    private javax.swing.JLabel lblHouse;
    private javax.swing.JLabel lblHouse1;
    private javax.swing.JLabel lblHouse6;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblName6;
    private javax.swing.JLabel lblUpdate;
    private javax.swing.JLabel lblagevali;
    private javax.swing.JLabel lblcityvali;
    private javax.swing.JLabel lblnamevali;
    private javax.swing.JTable tblPerson;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtAge1;
    private javax.swing.JTextField txtAge6;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCity1;
    private javax.swing.JTextField txtCity6;
    private javax.swing.JTextField txtCommunity;
    private javax.swing.JTextField txtCommunity1;
    private javax.swing.JTextField txtCommunity6;
    private javax.swing.JTextField txtHouse;
    private javax.swing.JTextField txtHouse1;
    private javax.swing.JTextField txtHouse6;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtName1;
    private javax.swing.JTextField txtName6;
    // End of variables declaration//GEN-END:variables

    protected void setDefaultOptions() {

        CreatePanel.setVisible(false);
        ViewPanel.setVisible(false);
        UpdatePanel.setVisible(false);
    }

    private void Update(Person person) {
        House house = person.getHouse();
        person.setPersonName(txtName6.getText());
        person.setAge(txtAge6.getText());
        house.setCityName(txtCity6.getText());
        house.setCommunityName(txtCommunity6.getText());
        house.setHouseNo(Integer.parseInt(txtHouse6.getText()));
        populateTable();

        txtName6.setText("");
        txtAge6.setText("");
        txtCity6.setText("");
        txtCommunity6.setText("");
        txtHouse6.setText("");
//        populateTable();
        revalidate();
        repaint();

    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblPerson.getModel();

        model.setRowCount(0);

        for (Person person : personDirectory.getPersonDirectory()) {
            House house = person.getHouse();

            Object[] row = new Object[10];
            row[0] = person;
            row[1] = person.getAge();
            row[2] = house.getCityName();
            row[3] = house.getCommunityName();
            row[4] = house.getHouseNo();
            model.addRow(row);

        }
    }
}
