/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;


import javax.swing.JOptionPane;
import model.Car;
import model.CarHistory;

/**
 *
 * @author sindhusrinivas
 */
public class CreateJPanel extends javax.swing.JPanel {

   
    CarHistory history;

    public CreateJPanel(CarHistory history) {
        initComponents();
        this.history = history;
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupRadio = new javax.swing.ButtonGroup();
        lblCreate = new javax.swing.JLabel();
        lblOccupy = new javax.swing.JLabel();
        lblBrand = new javax.swing.JLabel();
        lblYear = new javax.swing.JLabel();
        lblSeats = new javax.swing.JLabel();
        lblSerial = new javax.swing.JLabel();
        lblModel = new javax.swing.JLabel();
        lblCertificate = new javax.swing.JLabel();
        txtBrand = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        txtSeats = new javax.swing.JTextField();
        txtSerial = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        txtCertificate = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblRegister = new javax.swing.JLabel();
        txtRegister = new javax.swing.JTextField();
        chkYes = new javax.swing.JCheckBox();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        chkNo = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(0, 0, 0));

        lblCreate.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblCreate.setForeground(new java.awt.Color(255, 255, 255));
        lblCreate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreate.setText("ADD CAR ");

        lblOccupy.setBackground(new java.awt.Color(255, 255, 255));
        lblOccupy.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblOccupy.setForeground(new java.awt.Color(255, 255, 255));
        lblOccupy.setText("AVAILIBILITY");

        lblBrand.setBackground(new java.awt.Color(255, 255, 255));
        lblBrand.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblBrand.setForeground(new java.awt.Color(255, 255, 255));
        lblBrand.setText("BRAND");

        lblYear.setBackground(new java.awt.Color(255, 255, 255));
        lblYear.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblYear.setForeground(new java.awt.Color(255, 255, 255));
        lblYear.setText("MANUFACTURE YEAR");

        lblSeats.setBackground(new java.awt.Color(255, 255, 255));
        lblSeats.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSeats.setForeground(new java.awt.Color(255, 255, 255));
        lblSeats.setText("SEATS");

        lblSerial.setBackground(new java.awt.Color(255, 255, 255));
        lblSerial.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSerial.setForeground(new java.awt.Color(255, 255, 255));
        lblSerial.setText("SERIAL NUMBER");

        lblModel.setBackground(new java.awt.Color(255, 255, 255));
        lblModel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblModel.setForeground(new java.awt.Color(255, 255, 255));
        lblModel.setText("MODEL NUMBER");

        lblCertificate.setBackground(new java.awt.Color(255, 255, 255));
        lblCertificate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblCertificate.setForeground(new java.awt.Color(255, 255, 255));
        lblCertificate.setText("CERTIFICATE NUMBER");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblRegister.setBackground(new java.awt.Color(255, 255, 255));
        lblRegister.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblRegister.setForeground(new java.awt.Color(255, 255, 255));
        lblRegister.setText("REGISTRATION DATE");

        txtRegister.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRegisterKeyPressed(evt);
            }
        });

        chkYes.setForeground(new java.awt.Color(255, 255, 255));
        chkYes.setText("Yes");

        lblCity.setBackground(new java.awt.Color(255, 255, 255));
        lblCity.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblCity.setForeground(new java.awt.Color(255, 255, 255));
        lblCity.setText("CITY");

        chkNo.setForeground(new java.awt.Color(255, 255, 255));
        chkNo.setText("No");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSeats)
                                    .addComponent(lblSerial)
                                    .addComponent(lblModel)
                                    .addComponent(lblOccupy))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addComponent(btnSave))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(79, 79, 79)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtSerial, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(chkYes, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(chkNo))))))
                            .addComponent(lblBrand)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblYear)
                                    .addComponent(lblRegister)
                                    .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCertificate))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCertificate, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtYear, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                        .addComponent(txtCity)
                                        .addComponent(txtRegister)
                                        .addComponent(txtBrand))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegister)
                    .addComponent(txtRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCertificate)
                    .addComponent(txtCertificate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBrand)
                    .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYear)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblSeats))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblSerial))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSerial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModel)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOccupy)
                    .addComponent(chkYes)
                    .addComponent(chkNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
      // TODO add your handling code here:  
//      
//      String brand = txtBrand.getText();
//      String city = txtCity.getText();
//      String serialnumber = txtSerial.getText();
//      String registrationdate = txtRegister.getText();
//      String modelnumber = txtModel.getText();
//      String occupied = null;
//      int certificateyear = Integer.parseInt(txtCertificate.getText());
//      int year = Integer.parseInt(txtYear.getText());
//      int seats = Integer.parseInt(txtSeats.getText());
//      
//      if(chkYes.isSelected()){
//          occupied = "Yes";
//      }
//      else if(chkNo.isSelected())
//      {
//          occupied = "No";
//      }else
//      {
//          occupied = "No";
//      }
//            
        //Car CAR1 = history.addNewCar();
//        
//      CAR1.setRegistrationdate(registrationdate);
//      CAR1.setBrand(brand);
//      CAR1.setYear(year);
//      CAR1.setCity(city);
//      CAR1.setSeats(seats);
//      CAR1.setSerialnumber(serialnumber);
//      CAR1.setModelnumber(modelnumber);
//      CAR1.setCertificateyear(certificateyear);
//      CAR1.setOccupied(occupied);
//      
//      JOptionPane.showMessageDialog(this, "New Car Details added!");
//        
//        txtBrand.setText("");
//        txtCity.setText(" ");
//        txtSerial.setText(" ");
//        txtRegister.setText(" ");
//        txtModel.setText(" ");
//        txtCertificate.setText("");
//        txtYear.setText("");
//        txtSeats.setText(" ");
//        chkYes.setSelected(false);
//        chkNo.setSelected(false);
        
        
      
      
      if(txtRegister.getText().isEmpty() || txtBrand.getText().isEmpty() || txtYear.getText().isEmpty() 
              || txtCity.getText().isEmpty() || txtSeats.getText().isEmpty() || txtSerial.getText().isEmpty() 
              || txtModel.getText().isEmpty() || txtCertificate.getText().isEmpty())
      {
          JOptionPane.showMessageDialog(this, "NOT VALID INPUT..! ");
          return;
          
      }    
      String registrationdate = txtRegister.getText();
      String brand = txtBrand.getText();
      int year = Integer.parseInt(txtYear.getText());
      String city = txtCity.getText();
      int seats = Integer.parseInt(txtSeats.getText());
      String serialnumber = txtSerial.getText();
       
//      String serialregex = "^[A-Z a-z]{1,5}[0-9]{1,5}$";
//        if(!serialnumber.matches(serialregex) || (serialnumber.isEmpty())){
//            JOptionPane.showMessageDialog(this, "Not a Valid Serial Number!");
//        }
//        else{
//            CAR1.setSerialnumber(txtSerial.getText());
//        }

      
      String modelnumber = txtModel.getText();
      int certificateyear = Integer.parseInt(txtCertificate.getText());
      
      Car CAR = history.addNewCar();
      
      
      CAR.setRegistrationdate(registrationdate);
      CAR.setBrand(brand);
      CAR.setYear(year);
      CAR.setCity(city);
      CAR.setSeats(seats);
      CAR.setSerialnumber(serialnumber);
      CAR.setModelnumber(modelnumber);
      CAR.setCertificateyear(certificateyear);

        
    JOptionPane.showMessageDialog(this, "New Car Details added!");
      
       if(this.chkNo.isSelected()){
           CAR.setOccupied("yes"); 
        }

      txtBrand.setText("");
      txtYear.setText("");
      txtCity.setText("");
      txtSeats.setText("");
      txtSerial.setText("");
      txtModel.setText("");
      txtCertificate.setText("");
      txtRegister.setText(" ");
      
      
      
      
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtRegisterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRegisterKeyPressed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_txtRegisterKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroupRadio;
    private javax.swing.JCheckBox chkNo;
    private javax.swing.JCheckBox chkYes;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblCertificate;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCreate;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblOccupy;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JLabel lblSeats;
    private javax.swing.JLabel lblSerial;
    private javax.swing.JLabel lblYear;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtCertificate;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtRegister;
    private javax.swing.JTextField txtSeats;
    private javax.swing.JTextField txtSerial;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
