/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import model.Car;
import model.CarHistory;

/**
 *
 * @author sindhusrinivas
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    CarHistory history;
    
    public MainJFrame() {
        initComponents();
        
        history = new CarHistory();
      //  setData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPane = new javax.swing.JSplitPane();
        ControlPanel = new javax.swing.JPanel();
        btnCreate = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        WorkPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ControlPanel.setBackground(new java.awt.Color(153, 153, 153));

        btnCreate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCreate.setText("ADD");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnView.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnView.setText("VIEW");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSearch.setText("SEARCH");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ControlPanelLayout = new javax.swing.GroupLayout(ControlPanel);
        ControlPanel.setLayout(ControlPanelLayout);
        ControlPanelLayout.setHorizontalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        ControlPanelLayout.setVerticalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(btnCreate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnView)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch)
                .addContainerGap(586, Short.MAX_VALUE))
        );

        SplitPane.setLeftComponent(ControlPanel);

        WorkPanel.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout WorkPanelLayout = new javax.swing.GroupLayout(WorkPanel);
        WorkPanel.setLayout(WorkPanelLayout);
        WorkPanelLayout.setHorizontalGroup(
            WorkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 893, Short.MAX_VALUE)
        );
        WorkPanelLayout.setVerticalGroup(
            WorkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );

        SplitPane.setRightComponent(WorkPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
       // TODO add your handling code here:    
                
       CreateJPanel Createpanel = new CreateJPanel(history);
       SplitPane.setRightComponent(Createpanel);
               
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
         ViewJPanel Viewpanel = new ViewJPanel(history);
       SplitPane.setRightComponent(Viewpanel);
      
        
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        
       SearchJPanel Searchpanel = new SearchJPanel(history);
       SplitPane.setRightComponent(Searchpanel);
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

//    
//    public void setData(){
//     
//        Car CAR0 = history.addNewCar();
//        CAR0.setRegistration_date("2/10/2012");
//        CAR0.setOccupied("yes");
//        CAR0.setBrand("TESLA");
//        CAR0.setYear(2010);
//        CAR0.setCity("New York");
//        CAR0.setSeats(4);
//        CAR0.setSerial_number("TESLA98765");
//        CAR0.setModel_number("TES12");
//        CAR0.setCerti_year(2020);
//        CAR0.setTime("14-07-2017 04:24:27");
//        
//        
//        Car CAR = history.addNewCar();
//        CAR.setRegistration_date("2/10/2016");
//        CAR.setOccupied("yes");
//        CAR.setBrand("TOYOTA");
//        CAR.setYear(2012);
//        CAR.setCity("Bengaluru");
//        CAR.setSeats(8);
//        CAR.setSerial_number("TOY432");
//        CAR.setModel_number("TOY12");
//        CAR.setCerti_year(2022);
//        CAR.setTime("14-07-2017 04:24:27");
//        
//        Car CAR1 = history.addNewCar();
//        CAR1.setRegistration_date("23/12/2014");
//        CAR1.setOccupied("no");
//        CAR1.setBrand("BMW");
//        CAR1.setYear(2010);
//        CAR1.setCity("Boston");
//        CAR1.setSeats(5);
//        CAR1.setSerial_number("BMW876");
//        CAR1.setModel_number("BMW12");
//        CAR1.setCerti_year(2020);
//        CAR1.setTime("14-07-2017 04:24:27");
//        
//        
//        Car CAR3 = history.addNewCar();
//        CAR3.setRegistration_date("02/10/2021");
//        CAR3.setOccupied("yes");
//        CAR3.setBrand("BENZ");
//        CAR3.setYear(2019);
//        CAR3.setCity("Bengaluru");
//        CAR3.setSeats(5);
//        CAR3.setSerial_number("BEN432");
//        CAR3.setModel_number("BEN12");
//        CAR3.setCerti_year(2025);
//        CAR3.setTime("14-07-2017 04:24:27");
//          
//        
//        Car CAR4 = history.addNewCar();
//        CAR4.setRegistration_date("02/10/2015");
//        CAR4.setOccupied("yes");
//        CAR4.setBrand("FERRARI");
//        CAR4.setYear(2009);
//        CAR4.setCity("Texas");
//        CAR4.setSeats(5);
//        CAR4.setSerial_number("BEN432");
//        CAR4.setModel_number("FER12");
//        CAR4.setCerti_year(2019);
//        CAR4.setTime("14-07-2020 04:24:27");
//          
//    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ControlPanel;
    private javax.swing.JSplitPane SplitPane;
    private javax.swing.JPanel WorkPanel;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnView;
    // End of variables declaration//GEN-END:variables
}
