/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Car;
import model.CarHistory;

/**
 *
 * @author sindhusrinivas
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    CarHistory history;

    public ViewJPanel(CarHistory history) {
        initComponents();
        this.history = history;

        paneUpdate.setVisible(false);
        paneView.setVisible(false);

        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblView = new javax.swing.JLabel();
        table = new javax.swing.JScrollPane();
        tblCar = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnview = new javax.swing.JButton();
        paneView = new javax.swing.JPanel();
        lblRegister2 = new javax.swing.JLabel();
        txtRegister2 = new javax.swing.JTextField();
        lblOccupy2 = new javax.swing.JLabel();
        lblBrand2 = new javax.swing.JLabel();
        txtBrand2 = new javax.swing.JTextField();
        lblYear2 = new javax.swing.JLabel();
        txtYear2 = new javax.swing.JTextField();
        lblCity2 = new javax.swing.JLabel();
        txtCity2 = new javax.swing.JTextField();
        lblSeats2 = new javax.swing.JLabel();
        txtSeats2 = new javax.swing.JTextField();
        lblSerial2 = new javax.swing.JLabel();
        txtSerial2 = new javax.swing.JTextField();
        lblModel2 = new javax.swing.JLabel();
        txtModel2 = new javax.swing.JTextField();
        lblCertificate2 = new javax.swing.JLabel();
        txtCertificate2 = new javax.swing.JTextField();
        chkAvailability2 = new javax.swing.JCheckBox();
        paneUpdate = new javax.swing.JPanel();
        lblRegister = new javax.swing.JLabel();
        txtRegister = new javax.swing.JTextField();
        lblOccupy = new javax.swing.JLabel();
        chkAvailability = new javax.swing.JCheckBox();
        lblBrand = new javax.swing.JLabel();
        txtBrand = new javax.swing.JTextField();
        lblYear = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lblSeats = new javax.swing.JLabel();
        txtSeats = new javax.swing.JTextField();
        lblSerial = new javax.swing.JLabel();
        txtSerial = new javax.swing.JTextField();
        lblModel = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        lblCertificate = new javax.swing.JLabel();
        txtCertificate = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 0, 0));

        lblView.setBackground(new java.awt.Color(0, 0, 0));
        lblView.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblView.setForeground(new java.awt.Color(255, 255, 255));
        lblView.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblView.setText("VIEW ");

        tblCar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "AVAILABILITY", "BRAND", "MANUFACTURING DATE", "REGISTRATION DATE", "CITY", "SEATS", "SERIAL NUMBER", "MODEL NUMBER", "CERTIFICATE"
            }
        ));
        table.setViewportView(tblCar);

        btnDelete.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(51, 51, 51));
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnview.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnview.setText("VIEW");
        btnview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewActionPerformed(evt);
            }
        });

        paneView.setBackground(new java.awt.Color(204, 204, 204));

        lblRegister2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblRegister2.setText("REGISTRATION DATE");

        txtRegister2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegister2ActionPerformed(evt);
            }
        });

        lblOccupy2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblOccupy2.setText("AVAILIBILITY");

        lblBrand2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblBrand2.setText("BRAND");

        txtBrand2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrand2ActionPerformed(evt);
            }
        });

        lblYear2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblYear2.setText("MANUFACTURE YEAR");

        txtYear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYear2ActionPerformed(evt);
            }
        });

        lblCity2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblCity2.setText("CITY");

        txtCity2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCity2ActionPerformed(evt);
            }
        });

        lblSeats2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSeats2.setText("SEATS");

        txtSeats2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeats2ActionPerformed(evt);
            }
        });

        lblSerial2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSerial2.setText("SERIAL NUMBER");

        lblModel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblModel2.setText("MODEL NUMBER");

        txtModel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModel2ActionPerformed(evt);
            }
        });

        lblCertificate2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblCertificate2.setText("CERTIFICATE NUMBER");

        chkAvailability2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAvailability2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneViewLayout = new javax.swing.GroupLayout(paneView);
        paneView.setLayout(paneViewLayout);
        paneViewLayout.setHorizontalGroup(
            paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneViewLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneViewLayout.createSequentialGroup()
                        .addGroup(paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSerial2)
                            .addComponent(lblModel2)
                            .addComponent(lblOccupy2))
                        .addGap(100, 100, 100)
                        .addGroup(paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtModel2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSerial2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkAvailability2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(paneViewLayout.createSequentialGroup()
                        .addGroup(paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblYear2)
                            .addComponent(lblCity2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCertificate2)
                            .addComponent(lblBrand2)
                            .addComponent(lblSeats2)
                            .addComponent(lblRegister2))
                        .addGap(57, 57, 57)
                        .addGroup(paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRegister2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSeats2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBrand2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCertificate2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtYear2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCity2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        paneViewLayout.setVerticalGroup(
            paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneViewLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBrand2)
                    .addComponent(txtBrand2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCertificate2)
                    .addComponent(txtCertificate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeats2)
                    .addComponent(txtSeats2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYear2)
                    .addComponent(txtYear2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCity2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegister2)
                    .addComponent(txtRegister2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSerial2)
                    .addComponent(txtSerial2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModel2)
                    .addComponent(txtModel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblOccupy2)
                    .addComponent(chkAvailability2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneUpdate.setBackground(new java.awt.Color(51, 51, 51));

        lblRegister.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblRegister.setForeground(new java.awt.Color(255, 255, 255));
        lblRegister.setText("REGISTRATION DATE");

        txtRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegisterActionPerformed(evt);
            }
        });

        lblOccupy.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblOccupy.setForeground(new java.awt.Color(255, 255, 255));
        lblOccupy.setText("AVAILIBILITY");

        chkAvailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAvailabilityActionPerformed(evt);
            }
        });

        lblBrand.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblBrand.setForeground(new java.awt.Color(255, 255, 255));
        lblBrand.setText("BRAND");

        txtBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrandActionPerformed(evt);
            }
        });

        lblYear.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblYear.setForeground(new java.awt.Color(255, 255, 255));
        lblYear.setText("MANUFACTURE YEAR");

        txtYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYearActionPerformed(evt);
            }
        });

        lblCity.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblCity.setForeground(new java.awt.Color(255, 255, 255));
        lblCity.setText("CITY");

        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });

        lblSeats.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSeats.setForeground(new java.awt.Color(255, 255, 255));
        lblSeats.setText("SEATS");

        txtSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeatsActionPerformed(evt);
            }
        });

        lblSerial.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSerial.setForeground(new java.awt.Color(255, 255, 255));
        lblSerial.setText("SERIAL NUMBER");

        lblModel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblModel.setForeground(new java.awt.Color(255, 255, 255));
        lblModel.setText("MODEL NUMBER");

        txtModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelActionPerformed(evt);
            }
        });

        btnSubmit.setText("SUBMIT");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblCertificate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblCertificate.setForeground(new java.awt.Color(255, 255, 255));
        lblCertificate.setText("CERTIFICATE NUMBER");

        javax.swing.GroupLayout paneUpdateLayout = new javax.swing.GroupLayout(paneUpdate);
        paneUpdate.setLayout(paneUpdateLayout);
        paneUpdateLayout.setHorizontalGroup(
            paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneUpdateLayout.createSequentialGroup()
                .addGroup(paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneUpdateLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneUpdateLayout.createSequentialGroup()
                                .addGap(189, 189, 189)
                                .addComponent(btnSubmit)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(paneUpdateLayout.createSequentialGroup()
                                .addComponent(lblYear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(paneUpdateLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBrand)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneUpdateLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneUpdateLayout.createSequentialGroup()
                                .addComponent(lblOccupy)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(paneUpdateLayout.createSequentialGroup()
                                .addComponent(lblSeats)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(paneUpdateLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneUpdateLayout.createSequentialGroup()
                        .addComponent(lblRegister)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneUpdateLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSerial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSerial, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneUpdateLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCertificate)
                        .addGap(64, 64, 64)
                        .addComponent(txtCertificate, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneUpdateLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblModel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        paneUpdateLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtBrand, txtCertificate, txtCity, txtModel, txtRegister, txtSeats, txtSerial, txtYear});

        paneUpdateLayout.setVerticalGroup(
            paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneUpdateLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBrand)
                    .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCertificate)
                    .addComponent(txtCertificate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeats)
                    .addComponent(txtSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblYear)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegister)
                    .addComponent(txtRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSerial)
                    .addComponent(txtSerial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblModel)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblOccupy)
                    .addComponent(chkAvailability))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(btnSubmit)
                .addContainerGap())
        );

        paneUpdateLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtBrand, txtCertificate, txtCity, txtModel, txtRegister, txtSeats, txtSerial, txtYear});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(table))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(paneView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(paneUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnUpdate)
                                    .addComponent(btnview, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDelete))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDelete, btnUpdate, btnview});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblView, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(paneView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paneUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(table, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnview)
                .addGap(18, 18, 18)
                .addComponent(btnUpdate)
                .addGap(18, 18, 18)
                .addComponent(btnDelete)
                .addContainerGap(4939, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnDelete, btnUpdate, btnview});

    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:

        int selectedRowIndex = tblCar.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblCar.getModel();
        Car selectedCar = (Car) model.getValueAt(selectedRowIndex, 0);

        history.deleteCar(selectedCar);

        JOptionPane.showMessageDialog(this, "Car Details Deleted.");

        populateTable();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:

        int selectedRowIndex = tblCar.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to Update.");
            return;
        }

        paneView.setVisible(false);
        paneUpdate.setVisible(true);

        DefaultTableModel model = (DefaultTableModel) tblCar.getModel();
        Car selectedCar = (Car) model.getValueAt(selectedRowIndex, 0);
         if (String.valueOf(selectedCar.getOccupied()) == "yes") {
            chkAvailability.setSelected(true);
            chkAvailability.setText("");
        } else {
            chkAvailability.setSelected(false);
            chkAvailability.setText("");
        }
        txtRegister.setText(String.valueOf(selectedCar.getRegistrationdate()));
        txtBrand.setText(String.valueOf(selectedCar.getBrand()));
        txtYear.setText(String.valueOf(selectedCar.getYear()));
        txtCity.setText(String.valueOf(selectedCar.getCity()));
        txtSeats.setText(String.valueOf(selectedCar.getSeats()));
        txtSerial.setText(String.valueOf(selectedCar.getSerialnumber()));
        txtModel.setText(String.valueOf(selectedCar.getModelnumber()));
        txtCertificate.setText(String.valueOf(selectedCar.getCertificateyear()));


    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegisterActionPerformed

    private void chkAvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAvailabilityActionPerformed

    }//GEN-LAST:event_chkAvailabilityActionPerformed

    private void txtBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrandActionPerformed

    private void txtYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYearActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void txtSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeatsActionPerformed

    private void txtModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelActionPerformed

    private void btnviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewActionPerformed
        // TODO add your handling code here:

        int selectedRowIndex = tblCar.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Select Row to view");
            return;
        }
        paneUpdate.setVisible(false);
        paneView.setVisible(true);

        DefaultTableModel model = (DefaultTableModel) tblCar.getModel();
        Car selectedCar = (Car) model.getValueAt(selectedRowIndex, 0);
        if (String.valueOf(selectedCar.getOccupied()) == "yes") {
            chkAvailability2.setSelected(true);
            chkAvailability2.setText("");
        } else {
            chkAvailability2.setSelected(false);
            chkAvailability2.setText("");
        }
        txtRegister2.setText(String.valueOf(selectedCar.getRegistrationdate()));
        txtBrand2.setText(String.valueOf(selectedCar.getBrand()));
        txtYear2.setText(String.valueOf(selectedCar.getYear()));
        txtCity2.setText(String.valueOf(selectedCar.getCity()));
        txtSeats2.setText(String.valueOf(selectedCar.getSeats()));
        txtSerial2.setText(String.valueOf(selectedCar.getSerialnumber()));
        txtModel2.setText(String.valueOf(selectedCar.getModelnumber()));
        txtCertificate2.setText(String.valueOf(selectedCar.getCertificateyear()));

    }//GEN-LAST:event_btnviewActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:

        int selectedRowIndex = tblCar.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tblCar.getModel();
        Car selectedCar = (Car) model.getValueAt(selectedRowIndex, 0);
        Update(selectedCar);
        paneUpdate.setVisible(false);

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtRegister2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegister2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegister2ActionPerformed

    private void chkAvailability2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAvailability2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAvailability2ActionPerformed

    private void txtBrand2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrand2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrand2ActionPerformed

    private void txtYear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYear2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYear2ActionPerformed

    private void txtCity2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCity2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCity2ActionPerformed

    private void txtSeats2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeats2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeats2ActionPerformed

    private void txtModel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModel2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModel2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnview;
    private javax.swing.JCheckBox chkAvailability;
    private javax.swing.JCheckBox chkAvailability2;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblBrand2;
    private javax.swing.JLabel lblCertificate;
    private javax.swing.JLabel lblCertificate2;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCity2;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblModel2;
    private javax.swing.JLabel lblOccupy;
    private javax.swing.JLabel lblOccupy2;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JLabel lblRegister2;
    private javax.swing.JLabel lblSeats;
    private javax.swing.JLabel lblSeats2;
    private javax.swing.JLabel lblSerial;
    private javax.swing.JLabel lblSerial2;
    private javax.swing.JLabel lblView;
    private javax.swing.JLabel lblYear;
    private javax.swing.JLabel lblYear2;
    private javax.swing.JPanel paneUpdate;
    private javax.swing.JPanel paneView;
    private javax.swing.JScrollPane table;
    private javax.swing.JTable tblCar;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtBrand2;
    private javax.swing.JTextField txtCertificate;
    private javax.swing.JTextField txtCertificate2;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCity2;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtModel2;
    private javax.swing.JTextField txtRegister;
    private javax.swing.JTextField txtRegister2;
    private javax.swing.JTextField txtSeats;
    private javax.swing.JTextField txtSeats2;
    private javax.swing.JTextField txtSerial;
    private javax.swing.JTextField txtSerial2;
    private javax.swing.JTextField txtYear;
    private javax.swing.JTextField txtYear2;
    // End of variables declaration//GEN-END:variables

    private void Update(Car ch) {

        Date currentTime = new Date();
        DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
        String dateTime = dateFormat.format(currentTime);
        ch.setRegistrationdate(txtRegister.getText());
         if(this.chkAvailability.isSelected()){
           ch.setOccupied("yes"); 
        }else{
             ch.setOccupied("no"); 
         }
        ch.setBrand(txtBrand.getText());
        ch.setYear(Integer.parseInt(txtYear.getText()));
        ch.setSerialnumber(txtSerial.getText());
        ch.setSeats(Integer.parseInt(txtSeats.getText()));
        ch.setModelnumber(txtModel.getText());
        ch.setCity(txtCity.getText());
        ch.setCertificateyear(Integer.parseInt(txtCertificate.getText()));
        ch.setTime(dateTime);
        populateTable();

    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblCar.getModel();

        model.setRowCount(0);
//      System.out.println("size"+ history.getHistory().size());

        for (Car CAR : history.getHistory()) {

            Object[] row = new Object[10];
            row[0] = CAR;
            row[1] = CAR.getOccupied();
            row[2] = CAR.getBrand();
            row[3] = CAR.getYear();
            row[4] = CAR.getCity();
            row[5] = CAR.getSeats();
            row[6] = CAR.getSerialnumber();
            row[7] = CAR.getModelnumber();
            row[8] = CAR.getCertificateyear();

            model.addRow(row);

        }
    }

}
